
services:
  app:
    build: .

    depends_on:
      - mysql
      - redis
    
    container_name: zk-analytics-app
    ports:
      - '3000:3000'
    env_file:
      - .env

    command: npm run start:prod

  redis:
    image: redis:7
    restart: always
  mysql:
    image: mysql:8
    container_name: zk-analytics-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ..099009
      MYSQL_DATABASE: zkanalytics
      MYSQL_USER: zkuser
      MYSQL_PASSWORD: zkpass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
